# Change these first
owner: Nutreco # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: AquaSim Portal
    url: https://aquasim.skretting.com
  - name: SAM
    url: https://sam.skretting.com
  - name: XMS
    url: https://xms.skretting.com
  - name: AquaSim Authorization
    url: $SEC_LOGIN
  - name: Africa App
    url: https://aquasim-africa.skretting.com
  - name: Asia App
    url: https://aquasim-asia.skretting.com
  - name: APIM Developer
    url: https://apim-developer.skretting.com
    
  - name: AquaSim Portal UAT
    url: https://aquasimuat.skretting.com
  - name: SAM UAT
    url: https://samuat.skretting.com
  - name: XMS UAT
    url: https://xmsuat.skretting.com
  - name: AquaSim Authorization UAT
    url: $SEC_LOGIN_UAT
    maxResponseTime: 5000
  - name: Africa App UAT
    url: https://aquasimuat-africa.skretting.com
  - name: Asia App UAT
    url: https://aquasimuat-asia.skretting.com
  - name: APIM Developer UAT
    url: https://apimuat-developer.skretting.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime-status
  logoUrl: https://www.skretting.com/siteassets/images/logos/skretting-negative.png
  name: Skretting DI uptime monitor and status
  introTitle: Sketting DI "**uptime-status**"
  introMessage: This is a monitor & status page for all Skreting DI applications.
  navbar:
    - title: Status
      href: /
    - title: AquaSim Portal
      href: https://aquasim.skretting.com
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
